import sys
import asyncio
import base64
import os
import re
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

# 🔴 FIX: Streamlit ଇମ୍ପୋର୍ଟ ହେବା ପୂର୍ବରୁ ଏହାକୁ ରଖନ୍ତୁ (Windows Error ଫିକ୍ସ)
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

import streamlit as st
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, AIMessage
import db_manager

# Initialize the database on startup
db_manager.init_db()

# --- Page Configuration ---
st.set_page_config(
    page_title="TM Knowledge Bot", 
    page_icon="🏢", 
    layout="wide", 
    initial_sidebar_state="expanded"
)

# --- Session State Initialization ---
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
if "user_email" not in st.session_state:
    st.session_state.user_email = ""
if "current_session_id" not in st.session_state:
    st.session_state.current_session_id = None
if "stage" not in st.session_state:
    st.session_state.stage = "topic_selection"
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "topic" not in st.session_state:
    st.session_state.topic = ""
if "theme" not in st.session_state:
    st.session_state.theme = "Dark 🌙" 
if "main_notes" not in st.session_state:
    st.session_state.main_notes = None
if "quiz_book" not in st.session_state:
    st.session_state.quiz_book = None
if "certificate" not in st.session_state:
    st.session_state.certificate = None

# New States for Assessment & Flow
if "assessment_questions" not in st.session_state:
    st.session_state.assessment_questions = []
if "assessment_score" not in st.session_state:
    st.session_state.assessment_score = 0
if "assessment_grade" not in st.session_state:
    st.session_state.assessment_grade = ""

# ---------------------------------------------------------
# 🔴 ଲଗଇନ୍ ସିଷ୍ଟମ୍ (Login System)
# ---------------------------------------------------------
if not st.session_state.logged_in:
    st.title("🔐 Login to TM Knowledge Bot")
    st.markdown("Please log in or register to continue.")
    
    tab1, tab2 = st.tabs(["Login", "Register"])
    
    with tab1:
        l_email = st.text_input("Email ID", key="l_email")
        l_pass = st.text_input("Password", type="password", key="l_pass")
        if st.button("Login", use_container_width=True):
            if db_manager.authenticate_user(l_email, l_pass):
                st.session_state.logged_in = True
                st.session_state.user_email = l_email
                st.rerun()
            else:
                st.error("Invalid email or password.")
                
    with tab2:
        r_email = st.text_input("Email ID", key="r_email")
        r_pass = st.text_input("Password", type="password", key="r_pass")
        if st.button("Register", use_container_width=True):
            if r_email and r_pass:
                if db_manager.register_user(r_email, r_pass):
                    st.success("Registration successful! Please login from the Login tab.")
                else:
                    st.error("Email already exists. Try logging in.")
            else:
                st.error("Please fill in both fields.")
    st.stop()

# ମେନ୍ ଟାଇଟଲ୍ ଅପଡେଟ୍
st.title("TM Knowledge Bot")
st.markdown("Welcome to TM Knowledge Bot. Let's start your training journey!")

# --- Text/Markdown File Generation ---
def create_file(title, text_content):
    content = f"# {title}\n\n{text_content}\n\n---\n*Generated by AI Master Tutor*"
    return content.encode('utf-8')

# --- HTML Certificate Generation ---
def create_certificate(user_name, topic):
    logo_base64 = ""
    if os.path.exists("logo.png"):
        with open("logo.png", "rb") as image_file:
            logo_base64 = base64.b64encode(image_file.read()).decode()
            
    img_tag = f'<img class="logo" src="data:image/png;base64,{logo_base64}">' if logo_base64 else ''
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Certificate of Completion</title>
        <style>
            body {{ font-family: 'Arial', sans-serif; text-align: center; background-color: #f4f7f6; padding: 40px; }}
            .cert-container {{ background-color: white; border: 8px solid #c0392b; padding: 60px; max-width: 800px; margin: auto; box-shadow: 0 10px 30px rgba(0,0,0,0.1); border-radius: 10px; }}
            .logo {{ width: 180px; margin-bottom: 20px; }}
            h1 {{ font-size: 45px; color: #2c3e50; margin-bottom: 10px; font-family: 'Georgia', serif; text-transform: uppercase; letter-spacing: 2px; }}
            .subtitle {{ font-size: 20px; color: #7f8c8d; margin-bottom: 15px; }}
            .user-name {{ font-size: 38px; color: #2980b9; margin: 10px 0; font-weight: bold; font-family: 'Georgia', serif; text-decoration: underline; }}
            h2 {{ font-size: 40px; color: #c0392b; margin: 20px 0; padding-bottom: 10px; border-bottom: 2px solid #ecf0f1; display: inline-block; text-transform: uppercase; }}
            p {{ font-size: 18px; color: #555; line-height: 1.6; padding: 0 40px; }}
            .signature-area {{ margin-top: 60px; display: flex; justify-content: space-around; }}
            .signature-box {{ text-align: center; }}
            .signature-line {{ width: 200px; border-bottom: 2px solid #333; margin-bottom: 10px; }}
            .footer {{ margin-top: 40px; font-size: 12px; color: #95a5a6; }}
        </style>
    </head>
    <body>
        <div class="cert-container">
            {img_tag}
            <h1>Certificate of Completion</h1>
            <div class="subtitle">This is proudly presented to</div>
            <div class="user-name">{user_name}</div>
            <div class="subtitle">for successfully mastering</div>
            <h2>{topic}</h2>
            <p>You have demonstrated exceptional dedication by completing the comprehensive AI Masterclass, successfully passing the assessments, and showing a deep understanding of the subject matter.</p>
            
            <div class="signature-area">
                <div class="signature-box">
                    <div class="signature-line"></div>
                    <p><strong>AI Master Tutor</strong></p>
                </div>
                <div class="signature-box">
                    <div class="signature-line"></div>
                    <p><strong>Course Director</strong></p>
                </div>
            </div>
            
            <div class="footer">Generated automatically by AI Learning Platform &copy; 2026</div>
        </div>
    </body>
    </html>
    """
    return html_content.encode('utf-8')

# --- Auto Email Function (Only Score & Certificate) ---
def send_completion_email(user_email, score, total, grade, cert_bytes, topic):
    # ଏଠାରେ ଆପଣଙ୍କର ପ୍ରକୃତ ଇମେଲ୍ ଓ ଆପ୍ ପାସୱାର୍ଡ ଦେବେ
    sender_email = "your_email@gmail.com" 
    sender_password = "your_app_password" 
    
    msg = MIMEMultipart()
    msg['Subject'] = f'Your AI Master Tutor Results & Certificate - {topic}'
    msg['From'] = sender_email
    msg['To'] = user_email
    
    body = f"""
    Hello,

    Congratulations on completing the Masterclass for {topic}!

    Here is your Final Scoreboard:
    Score: {score} out of {total}
    Grade: {grade}

    Please find attached your Certificate of Completion (Open in browser to Print as PDF).

    Best Regards,
    TM Knowledge Bot
    """
    msg.attach(MIMEText(body, 'plain'))
    
    # Attach Certificate Only
    part_cert = MIMEApplication(cert_bytes, Name=f"{topic}_Certificate.html")
    part_cert['Content-Disposition'] = f'attachment; filename="{topic}_Certificate.html"'
    msg.attach(part_cert)
    
    try:
        # ଇମେଲ୍ ପଠାଇବା ପାଇଁ ତଳ ୩ ଲାଇନ୍ ରୁ '#' ହଟାଇଦେବେ
        # with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
        #     server.login(sender_email, sender_password)
        #     server.sendmail(sender_email, [user_email], msg.as_string())
        return True 
    except Exception as e:
        print("Email sending failed:", e)
        return False

# --- ADVANCED CSS ---
common_css = """
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');
    
    .stApp, p, h1, h2, h3, h4, label, li { font-family: 'Plus Jakarta Sans', sans-serif !important; }
    
    .gemini-greeting {
        background: linear-gradient(300deg, #4285f4, #9b72cb, #d96570, #f39c12);
        background-size: 240% 240%;
        animation: gradient-animation 6s ease infinite;
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-size: 3.8rem !important;
        font-weight: 700 !important;
        margin-bottom: 0px !important;
        letter-spacing: -1px;
    }
    @keyframes gradient-animation { 0% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } 100% { background-position: 0% 50%; } }
    [data-testid="stChatMessage"] { background-color: transparent !important; border: none !important; box-shadow: none !important; padding: 1rem 0 !important; }
    [data-testid="stBottomBlock"], [data-testid="stBottom"] { background: transparent !important; }
    .stChatInputContainer { border-radius: 20px !important; padding: 8px 18px !important; border: 1px solid rgba(100, 100, 100, 0.3) !important; box-shadow: 0 8px 24px rgba(0,0,0,0.08) !important; transition: all 0.3s ease; }
    .stChatInputContainer:focus-within { border-color: #4285f4 !important; box-shadow: 0 8px 32px rgba(66, 133, 244, 0.15) !important; }
    .stButton>button { border-radius: 12px !important; transition: all 0.25s ease !important; font-weight: 600 !important; }
    .stButton>button:hover { transform: translateY(-2px); box-shadow: 0 6px 16px rgba(0,0,0,0.12); }
    footer, #MainMenu { display: none !important; }
    [data-testid="stHeader"] { background-color: transparent !important; }
"""

if st.session_state.theme == "Light ☀️":
    theme_css = f"""<style>{common_css} [data-testid="stAppViewContainer"] {{ background-color: #FAFAFB !important; }} [data-testid="stSidebar"] {{ background-color: #FFFFFF !important; border-right: 1px solid #F0F0F0 !important; }} .stMarkdown, p, span, h1, h2, h3, h4, label {{ color: #1E1E1E !important; }} .stChatInput textarea {{ background-color: #FFFFFF !important; color: #1E1E1E !important; }} .stChatInputContainer {{ background-color: #FFFFFF !important; }}</style>"""
else:
    theme_css = f"""<style>{common_css} [data-testid="stAppViewContainer"] {{ background-color: #0E1117 !important; }} [data-testid="stSidebar"] {{ background-color: #161A23 !important; border-right: 1px solid #262B35 !important; }} .stMarkdown, p, span, h1, h2, h3, h4, label {{ color: #F0F2F6 !important; }} .stChatInput textarea {{ background-color: #161A23 !important; color: #F0F2F6 !important; }} .stChatInputContainer {{ background-color: #161A23 !important; border-color: #313642 !important; }}</style>"""
st.markdown(theme_css, unsafe_allow_html=True)

# --- Sidebar ---
with st.sidebar:
    logo_path = "logo.png"
    if os.path.exists(logo_path):
        with open(logo_path, "rb") as image_file:
            encoded_string = base64.b64encode(image_file.read()).decode()
        
        st.markdown(
            f"""
            <div style="background-color: #FFFFFF; padding: 15px; border-radius: 12px; margin-bottom: 25px; text-align: center; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
                <img src="data:image/png;base64,{encoded_string}" width="160">
            </div>
            """,
            unsafe_allow_html=True
        )
    else:
        st.error("⚠️ Please add 'logo.png' to your folder!")

    st.markdown("### 🤖 Bot Mode")
    app_mode = st.radio("Select Mode:", ["💬 Casual Chat", "📚 Study Masterclass"], key="app_mode", label_visibility="collapsed")
    
    st.markdown("---")
    st.markdown("### ⚙️ System Settings")
    selected_language = st.selectbox("🌐 Choose Output Language:", ["English", "Odia", "Hindi", "Bengali", "Spanish"])
    st.radio("Select Theme:", ["Light ☀️", "Dark 🌙"], horizontal=True, key="theme", label_visibility="collapsed")
    st.markdown("---")

    if st.button("✨ Start New Journey", use_container_width=True):
        st.session_state.current_session_id = None
        st.session_state.chat_history = []
        st.session_state.stage = "topic_selection"
        st.session_state.topic = "" 
        st.session_state.main_notes = None  
        st.session_state.quiz_book = None 
        st.session_state.certificate = None
        st.session_state.assessment_questions = []
        st.rerun()

    st.markdown("### 📚 Study History")
    past_sessions = db_manager.get_all_sessions()
    if past_sessions:
        for session in past_sessions:
            col1, col2 = st.columns([4, 1])
            with col1:
                topic_name = session['topic'] if len(session['topic']) < 18 else session['topic'][:15] + "..."
                if st.button(f"📖 {topic_name}", key=f"load_{session['session_id']}", use_container_width=True):
                    st.session_state.current_session_id = session['session_id']
                    st.session_state.topic = session['topic']
                    raw_messages = db_manager.get_messages_for_session(session['session_id'])
                    st.session_state.chat_history = []
                    for msg in raw_messages:
                        if msg["role"] == "user":
                            st.session_state.chat_history.append(HumanMessage(content=msg["content"]))
                        else:
                            st.session_state.chat_history.append(AIMessage(content=msg["content"]))
                    st.session_state.main_notes = None  
                    st.session_state.quiz_book = None
                    st.session_state.certificate = None
                    st.session_state.stage = "topic_selection" 
                    st.rerun()
            with col2:
                if st.button("🗑️", key=f"del_{session['session_id']}", help="Delete this session"):
                    db_manager.delete_session(session['session_id'])
                    if st.session_state.current_session_id == session['session_id']:
                        st.session_state.current_session_id = None
                        st.session_state.chat_history = []
                        st.session_state.stage = "topic_selection"
                        st.session_state.topic = ""
                    st.rerun()

    if st.button("🚪 Logout", use_container_width=True):
        st.session_state.logged_in = False
        st.session_state.user_email = ""
        st.rerun()

# --- Main Interface Chat History ---
if not st.session_state.chat_history and st.session_state.current_session_id is None:
    st.markdown("<br><br><br>", unsafe_allow_html=True)
    if st.session_state.app_mode == "💬 Casual Chat":
        st.markdown(f"<h3 style='color: {'#737B8B' if st.session_state.theme == 'Light ☀️' else '#8B949E'}; font-weight: 400; letter-spacing: 0.5px;'>Let's chat! I'm here to talk about anything.</h3>", unsafe_allow_html=True)
    else:
        st.markdown(f"<h3 style='color: {'#737B8B' if st.session_state.theme == 'Light ☀️' else '#8B949E'}; font-weight: 400; letter-spacing: 0.5px;'>Tell me a topic to create a Master Course.</h3>", unsafe_allow_html=True)
    st.markdown("<br>", unsafe_allow_html=True)

for msg in st.session_state.chat_history:
    role = "user" if isinstance(msg, HumanMessage) else "assistant"
    avatar_icon = "👤" if role == "user" else "🤖"
    with st.chat_message(role, avatar=avatar_icon):
        st.markdown(msg.content)

# ---------------------------------------------------------
# 🔴 UI Flow (Materials -> Assessment -> Certificate -> Download)
# ---------------------------------------------------------
if st.session_state.stage == "generating_materials":
    with st.spinner("Generating 5-6 pages of Deep Reading Notes and Practice Quiz..."):
        llm_dl = ChatOllama(model="llama3.2:1b", temperature=0.5)
        
        # Notes prompt
        notes_prompt = f"""
        Create a VERY DEEP, MASSIVE, and COMPREHENSIVE study document for '{st.session_state.topic}' in {selected_language}.
        This document must be equivalent to 5-6 pages (at least 2000 words).
        Include exhaustive history, deep architectural breakdowns, multiple code/real-world examples, advanced concepts, and pitfall analysis.
        Use clear headings, bullet points, and structure.
        """
        notes_response = llm_dl.invoke(notes_prompt)
        st.session_state.main_notes = create_file(f"{st.session_state.topic} - Main Notes", notes_response.content)
        
        # Quiz prompt
        quiz_prompt = f"Create a practice test paper with exactly 10 Multiple Choice Questions (MCQs) and their Answer Key for '{st.session_state.topic}' in {selected_language}."
        quiz_response = llm_dl.invoke(quiz_prompt)
        st.session_state.quiz_book = create_file(f"{st.session_state.topic} - Practice Quiz", quiz_response.content)
        
        st.session_state.stage = "materials_ready"
        st.rerun()

elif st.session_state.stage == "materials_ready":
    st.markdown("### 📥 Download Your Study Materials First")
    st.info("Please download and study these materials before taking the Final Assessment.")
    col_a, col_b = st.columns(2)
    with col_a:
        st.download_button(
            label="📄 Download 5-6 Page Reading Notes",
            data=st.session_state.main_notes,
            file_name=f"{st.session_state.topic}_Notes.md",
            mime="text/markdown",
            use_container_width=True
        )
    with col_b:
        st.download_button(
            label="📝 Download Practice Quiz",
            data=st.session_state.quiz_book,
            file_name=f"{st.session_state.topic}_Practice_Quiz.md",
            mime="text/markdown",
            use_container_width=True
        )
    
    st.markdown("---")
    if st.button("🚀 I have read the materials. Start Final Assessment!", use_container_width=True):
        st.session_state.stage = "generating_assessment"
        st.rerun()

elif st.session_state.stage == "generating_assessment":
    with st.spinner("Generating Final Assessment... (This may take a moment)"):
        llm_assess = ChatOllama(model="llama3.2:1b", temperature=0.3)
        
        # ଟିକେ ସହଜ ପ୍ରମ୍ପ୍ଟ ଦେବା ଯାହାଦ୍ୱାରା ମଡେଲ୍ କନଫ୍ୟୁଜ୍ ହେବନି
        q_prompt = f"""
        Generate multiple-choice questions about '{st.session_state.topic}' in {selected_language}.
        Try to generate up to 25 questions.
        You MUST follow this exact plain text format for every single question:
        Q: [Question text]
        A) [Option A]
        B) [Option B]
        C) [Option C]
        D) [Option D]
        Answer: [A, B, C, or D]

        Do NOT use markdown bolding (like **Q:**). Just plain text.
        """
        
        resp = llm_assess.invoke(q_prompt)
        
        # ଯଦି AI ଭୁଲ୍ ରେ Bold କରିଦେଇଥାଏ, ତେବେ ତାକୁ ହଟାଇଦେବା
        raw_text = resp.content.replace('**', '')
        questions = []
        
        # Regex ବ୍ୟବହାର କରି ବିଭିନ୍ନ ପ୍ରକାରର ପ୍ରଶ୍ନ ଫର୍ମାଟ୍ କୁ ଧରିବା (Q:, 1., Q1: ଇତ୍ୟାଦି)
        blocks = re.split(r'(?:^Q\d*\s*:|^Question\d*\s*:|^\d+\.)', raw_text, flags=re.MULTILINE | re.IGNORECASE)
        
        if len(blocks) < 2:
            blocks = raw_text.split('Q:')
            
        for block in blocks:
            lines = [line.strip() for line in block.strip().split('\n') if line.strip()]
            if not lines or len(lines) < 3:
                continue
                
            q_text = lines[0]
            options = []
            ans = ""
            
            for line in lines[1:]:
                # Option ଗୁଡିକୁ ଧରିବା (A), B. ଇତ୍ୟାଦି)
                if re.match(r'^[A-D][\.\)]', line, re.IGNORECASE):
                    options.append(line)
                # Answer କୁ ଧରିବା (Ans: A କିମ୍ବା Answer: A)
                elif re.search(r'(?:Ans|Answer).*?([A-D])', line, re.IGNORECASE):
                    match = re.search(r'(?:Ans|Answer).*?([A-D])', line, re.IGNORECASE)
                    if match:
                        ans = match.group(1).upper()
            
            # ଅତିକମରେ ୨ଟି ଅପ୍ସନ୍ ଏବଂ ଗୋଟିଏ ଉତ୍ତର ଥିଲେ ହିଁ ଗ୍ରହଣ କରିବା
            if len(options) >= 2 and ans:
                questions.append({'q': q_text, 'options': options, 'ans': ans})
        
        # ଯଦି ଅତିକମରେ କିଛି ପ୍ରଶ୍ନ ତିଆରି ହୋଇଛି ତେବେ ଆଗକୁ ବଢିବା
        if len(questions) > 0:
            st.session_state.assessment_questions = questions
            st.session_state.stage = "taking_assessment"
            st.rerun()
        else:
            # ଯଦି ବିଲକୁଲ୍ ଗୋଟେ ବି ପ୍ରଶ୍ନ ପଢିପାରିଲାନି, ତେବେ ଏରର୍ ଦେଖାଇବ
            pass

elif st.session_state.stage == "taking_assessment":
    st.markdown("### 📝 Final Assessment (25 Questions)")
    if not st.session_state.assessment_questions:
        st.error("Failed to generate questions properly. Please try again.")
        if st.button("Retry"):
            st.session_state.stage = "generating_assessment"
            st.rerun()
    else:
        with st.form("assessment_form"):
            user_answers = {}
            for i, q in enumerate(st.session_state.assessment_questions):
                st.markdown(f"**Q{i+1}: {q['q']}**")
                user_answers[i] = st.radio("Select Answer:", q['options'], key=f"q_{i}", index=None)
                st.markdown("---")
            
            submitted = st.form_submit_button("Submit Assessment")
            if submitted:
                score = 0
                for i, q in enumerate(st.session_state.assessment_questions):
                    selected = user_answers[i]
                    if selected and selected.startswith(q['ans']):
                        score += 1
                
                st.session_state.assessment_score = score
                total = len(st.session_state.assessment_questions)
                percentage = (score / total) * 100 if total > 0 else 0
                
                if percentage >= 90: grade = "O (Outstanding)"
                elif percentage >= 80: grade = "E (Excellent)"
                elif percentage >= 70: grade = "A (Very Good)"
                elif percentage >= 60: grade = "B (Good)"
                else: grade = "C (Average)"
                
                st.session_state.assessment_grade = grade
                st.session_state.stage = "assessment_completed"
                st.rerun()

elif st.session_state.stage == "assessment_completed":
    total = len(st.session_state.assessment_questions)
    st.markdown("### 🏆 Final Scoreboard")
    col_score, col_grade = st.columns(2)
    with col_score:
        st.info(f"### Score: {st.session_state.assessment_score} / {total}")
    with col_grade:
        st.success(f"### Grade: {st.session_state.assessment_grade}")
    
    st.markdown("---")
    st.markdown("### 🎓 Claim Your Certificate")
    cert_name = st.text_input("Enter your name for the Certificate:")
    
    if st.button("Generate & Send Certificate", use_container_width=True):
        if cert_name.strip() == "":
            st.error("⚠️ ଦୟାକରି ସାର୍ଟିଫିକେଟ୍ ପାଇଁ ପ୍ରଥମେ ନିଜର ନାମ ଲେଖନ୍ତୁ!")
        else:
            with st.spinner("Generating Certificate and Sending Email..."):
                # Generate Certificate
                st.session_state.certificate = create_certificate(cert_name, st.session_state.topic)
                
                # Send Email (Only Cert & Score)
                email_sent = send_completion_email(
                    st.session_state.user_email,
                    st.session_state.assessment_score,
                    total,
                    st.session_state.assessment_grade,
                    st.session_state.certificate,
                    st.session_state.topic
                )
                
                if email_sent:
                    st.success(f"✅ Your Score and Certificate have been automatically emailed to {st.session_state.user_email}!")
                else:
                    st.warning("⚠️ Email delivery is set up but requires valid SMTP credentials in the code.")
                
                st.session_state.stage = "certificate_ready"
                st.rerun()

elif st.session_state.stage == "certificate_ready":
    st.markdown("### 🎉 Congratulations! Your Journey is Complete.")
    st.download_button(
        label="⬇️ Download Your Certificate Now",
        data=st.session_state.certificate,
        file_name=f"{st.session_state.topic}_Certificate.html",
        mime="text/html",
        use_container_width=True
    )

# --- User Input Chat Logic ---
# UI ଷ୍ଟେଜ୍ ଚାଲିଥିବା ବେଳେ ଚାଟ୍ ଇନପୁଟ୍ ବନ୍ଦ ରହିବ
hidden_stages = ["generating_materials", "materials_ready", "generating_assessment", "taking_assessment", "assessment_completed", "certificate_ready"]

if st.session_state.stage not in hidden_stages:
    user_input = st.chat_input("Ask anything or enter your response...")

    if user_input:
        llm = ChatOllama(model="llama3.2:1b", temperature=0.4)

        if st.session_state.current_session_id is None:
            st.session_state.current_session_id = db_manager.create_new_session(topic=user_input)
            st.session_state.topic = user_input
            
        st.session_state.chat_history.append(HumanMessage(content=user_input))
        db_manager.save_message(st.session_state.current_session_id, "user", user_input)
        
        with st.chat_message("user", avatar="👤"):
            st.markdown(user_input)
            
        with st.chat_message("assistant", avatar="🤖"):
            with st.spinner("Thinking..."):
                try:
                    if st.session_state.app_mode == "💬 Casual Chat":
                        chat_prompt = f"""
                        You are a friendly, conversational AI companion.
                        Respond naturally and warmly to the user's input: '{user_input}'.
                        CRITICAL RULE: Respond ENTIRELY in the {selected_language} language.
                        Do not teach or provide educational levels unless explicitly asked.
                        """
                        response = llm.invoke(chat_prompt)
                        st.markdown(response.content)

                    else:
                        persona_instruction = f"""
                        You are an advanced AI Master Tutor. 
                        CRITICAL RULES:
                        1. Respond ENTIRELY in the {selected_language} language.
                        2. Never print your internal tags or instructions.
                        3. Keep your response clean and well-formatted.
                        """
                        
                        if st.session_state.stage == "topic_selection":
                            prompt = f"""
                            The user wants to learn about: '{user_input}'.
                            {persona_instruction}
                            YOUR TASK: Introduce the topic and show Beginner, Intermediate, and Advanced levels in a Markdown table.
                            End your response EXACTLY with a new line saying: "Which level or levels would you like to study?" Add the exact tag [LEARN] at the end.
                            """
                            response = llm.invoke(prompt)
                            reply_text = response.content
                            if "[LEARN]" in reply_text or "Beginner Level" in reply_text or "Intermediate Level" in reply_text:
                                st.session_state.stage = "level_selection"
                            reply_text = reply_text.replace("[LEARN]", "").strip()
                            st.markdown(reply_text)
                            response.content = reply_text

                        elif st.session_state.stage == "level_selection":
                            prompt = f"""
                            Topic: '{st.session_state.topic}'. Levels chosen: '{user_input}'.
                            {persona_instruction}
                            YOUR TASK: Create a detailed Study Schedule in a Markdown table format.
                            End EXACTLY with: "Please reply 'Start' whenever you are ready to begin the lesson."
                            """
                            response = llm.invoke(prompt)
                            st.markdown(response.content)
                            st.session_state.stage = "wait_for_start"

                        elif st.session_state.stage == "wait_for_start":
                            if any(word in user_input.lower() for word in ["start", "yes", "ok", "ready", "ହଁ", "ଆରମ୍ଭ"]):
                                prompt = f"""
                                Topic: '{st.session_state.topic}'
                                {persona_instruction}
                                
                                YOUR TASK:
                                You are writing a comprehensive, university-level textbook chapter on this topic. 
                                You MUST provide a MASSIVE, EXHAUSTIVE, and EXTREMELY DEEP explanation. 
                                Do NOT summarize. Expand on EVERY single point as much as possible.
                                
                                Structure your massive response strictly as follows:
                                1. **Deep Introduction & History**
                                2. **Exhaustive Breakdown**
                                3. **Real-World Scenarios**
                                4. **Extensive Code Blocks** (if technical)
                                5. **Advanced Concepts & Best Practices**
                                6. **Common Pitfalls**
                                
                                CRITICAL: Your output must be very long and detailed. Use bullet points, bold text, and proper line breaks. 
                                End your massive explanation EXACTLY with a new line saying: "Please reply 'Materials' to download your 5-6 page reading notes and practice quiz."
                                """
                                response = llm.invoke(prompt)
                                st.session_state.stage = "wait_for_materials_trigger"
                            else:
                                prompt = f"Politely tell the user to reply 'Start' when they are ready to read the full explanation. {persona_instruction}"
                                response = llm.invoke(prompt)
                            st.markdown(response.content)

                        elif st.session_state.stage == "wait_for_materials_trigger":
                            if any(word in user_input.lower() for word in ["material", "materials", "notes", "quiz", "yes", "ok", "ready", "ହଁ"]):
                                st.session_state.stage = "generating_materials"
                                st.rerun()
                            else:
                                prompt = f"Politely tell the user to reply 'Materials' to get their notes and quiz. {persona_instruction}"
                                response = llm.invoke(prompt)
                                st.markdown(response.content)
                    
                    if st.session_state.stage not in ["generating_materials"]:
                        st.session_state.chat_history.append(AIMessage(content=response.content))
                        db_manager.save_message(st.session_state.current_session_id, "assistant", response.content)

                except Exception as e:
                    st.error(f"⚠️ Engine Error: {str(e)}\n\n(Ensure your local AI engine is running in the terminal.)")
                    st.session_state.chat_history.pop()
