import sys
import asyncio

# 🔴 FIX: Streamlit ଇମ୍ପୋର୍ଟ ହେବା ପୂର୍ବରୁ ଏହାକୁ ରଖନ୍ତୁ (Windows Error ଫିକ୍ସ)
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

import streamlit as st
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, AIMessage
import db_manager

# Initialize the database on startup
db_manager.init_db()

# --- Page Configuration ---
st.set_page_config(page_title="AI Master Tutor", page_icon="🤖", layout="wide", initial_sidebar_state="expanded")

# --- Session State Initialization ---
if "current_session_id" not in st.session_state:
    st.session_state.current_session_id = None
if "stage" not in st.session_state:
    st.session_state.stage = "topic_selection"
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "topic" not in st.session_state:
    st.session_state.topic = ""
if "theme" not in st.session_state:
    st.session_state.theme = "Dark 🌙" 

# ଡାଉନଲୋଡ୍ ଫାଇଲ୍ ଗୁଡିକୁ ମନେ ରଖିବା ପାଇଁ
if "main_notes" not in st.session_state:
    st.session_state.main_notes = None
if "quiz_book" not in st.session_state:
    st.session_state.quiz_book = None

# --- Text/Markdown File Generation ---
def create_file(title, text_content):
    content = f"# {title}\n\n{text_content}\n\n---\n*Generated by AI Master Tutor*"
    return content.encode('utf-8')

# --- ADVANCED CSS ---
common_css = """
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');
    .stApp, div, span, p, h1, h2, h3, h4, label, button { font-family: 'Plus Jakarta Sans', sans-serif !important; }
    .gemini-greeting {
        background: linear-gradient(300deg, #4285f4, #9b72cb, #d96570, #f39c12);
        background-size: 240% 240%;
        animation: gradient-animation 6s ease infinite;
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-size: 3.8rem !important;
        font-weight: 700 !important;
        margin-bottom: 0px !important;
        letter-spacing: -1px;
    }
    @keyframes gradient-animation { 0% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } 100% { background-position: 0% 50%; } }
    [data-testid="stChatMessage"] { background-color: transparent !important; border: none !important; box-shadow: none !important; padding: 1rem 0 !important; }
    [data-testid="stBottomBlock"], [data-testid="stBottom"] { background: transparent !important; }
    .stChatInputContainer { border-radius: 20px !important; padding: 8px 18px !important; border: 1px solid rgba(100, 100, 100, 0.3) !important; box-shadow: 0 8px 24px rgba(0,0,0,0.08) !important; transition: all 0.3s ease; }
    .stChatInputContainer:focus-within { border-color: #4285f4 !important; box-shadow: 0 8px 32px rgba(66, 133, 244, 0.15) !important; }
    .stButton>button { border-radius: 12px !important; transition: all 0.25s ease !important; font-weight: 600 !important; }
    .stButton>button:hover { transform: translateY(-2px); box-shadow: 0 6px 16px rgba(0,0,0,0.12); }
    footer, #MainMenu, [data-testid="stHeader"] { display: none !important; }
"""

if st.session_state.theme == "Light ☀️":
    theme_css = f"""<style>{common_css} [data-testid="stAppViewContainer"] {{ background-color: #FAFAFB !important; }} [data-testid="stSidebar"] {{ background-color: #FFFFFF !important; border-right: 1px solid #F0F0F0 !important; }} .stMarkdown, p, span, h1, h2, h3, h4, label {{ color: #1E1E1E !important; }} .stChatInput textarea {{ background-color: #FFFFFF !important; color: #1E1E1E !important; }} .stChatInputContainer {{ background-color: #FFFFFF !important; }}</style>"""
else:
    theme_css = f"""<style>{common_css} [data-testid="stAppViewContainer"] {{ background-color: #0E1117 !important; }} [data-testid="stSidebar"] {{ background-color: #161A23 !important; border-right: 1px solid #262B35 !important; }} .stMarkdown, p, span, h1, h2, h3, h4, label {{ color: #F0F2F6 !important; }} .stChatInput textarea {{ background-color: #161A23 !important; color: #F0F2F6 !important; }} .stChatInputContainer {{ background-color: #161A23 !important; border-color: #313642 !important; }}</style>"""
st.markdown(theme_css, unsafe_allow_html=True)

# --- Sidebar ---
with st.sidebar:
    st.markdown("### 🤖 Bot Mode")
    # 🔴 ନୂଆ ଫିଚର୍: Mode Selection 
    app_mode = st.radio("Select Mode:", ["💬 Casual Chat", "📚 Study Masterclass"], key="app_mode", label_visibility="collapsed")
    
    st.markdown("---")
    st.markdown("### ⚙️ System Settings")
    selected_language = st.selectbox("🌐 Choose Output Language:", ["English", "Odia", "Hindi", "Bengali", "Spanish"])
    st.radio("Select Theme:", ["Light ☀️", "Dark 🌙"], horizontal=True, key="theme", label_visibility="collapsed")
    st.markdown("---")

    if st.button("✨ Start New Journey", use_container_width=True):
        st.session_state.current_session_id = None
        st.session_state.chat_history = []
        st.session_state.stage = "topic_selection"
        st.session_state.topic = ""
        st.session_state.main_notes = None  
        st.session_state.quiz_book = None   
        st.rerun()

    st.markdown("### 📚 Study History")
    past_sessions = db_manager.get_all_sessions()
    if past_sessions:
        for session in past_sessions:
            col1, col2 = st.columns([4, 1])
            with col1:
                topic_name = session['topic'] if len(session['topic']) < 18 else session['topic'][:15] + "..."
                if st.button(f"📖 {topic_name}", key=f"load_{session['session_id']}", use_container_width=True):
                    st.session_state.current_session_id = session['session_id']
                    st.session_state.topic = session['topic']
                    raw_messages = db_manager.get_messages_for_session(session['session_id'])
                    st.session_state.chat_history = []
                    for msg in raw_messages:
                        if msg["role"] == "user":
                            st.session_state.chat_history.append(HumanMessage(content=msg["content"]))
                        else:
                            st.session_state.chat_history.append(AIMessage(content=msg["content"]))
                    st.session_state.main_notes = None  
                    st.session_state.quiz_book = None   
                    st.rerun()
            with col2:
                if st.button("🗑️", key=f"del_{session['session_id']}", help="Delete this session"):
                    db_manager.delete_session(session['session_id'])
                    if st.session_state.current_session_id == session['session_id']:
                        st.session_state.current_session_id = None
                        st.session_state.chat_history = []
                        st.session_state.stage = "topic_selection"
                        st.session_state.topic = ""
                    st.rerun()

# --- Main Interface ---
if not st.session_state.chat_history and st.session_state.current_session_id is None:
    st.markdown("<br><br><br>", unsafe_allow_html=True)
    st.markdown("<h1 class='gemini-greeting'>Hello there.</h1>", unsafe_allow_html=True)
    if st.session_state.app_mode == "💬 Casual Chat":
        st.markdown(f"<h3 style='color: {'#737B8B' if st.session_state.theme == 'Light ☀️' else '#8B949E'}; font-weight: 400; letter-spacing: 0.5px;'>Let's chat! I'm here to talk about anything.</h3>", unsafe_allow_html=True)
    else:
        st.markdown(f"<h3 style='color: {'#737B8B' if st.session_state.theme == 'Light ☀️' else '#8B949E'}; font-weight: 400; letter-spacing: 0.5px;'>Tell me a topic to create a Master Course.</h3>", unsafe_allow_html=True)
    st.markdown("<br>", unsafe_allow_html=True)

for msg in st.session_state.chat_history:
    role = "user" if isinstance(msg, HumanMessage) else "assistant"
    avatar_icon = "👤" if role == "user" else "🤖"
    with st.chat_message(role, avatar=avatar_icon):
        st.markdown(msg.content)

# ଡାଉନଲୋଡ୍ ବଟନ୍ ବିଭାଗ (କେବଳ Study Mode ରେ ଦେଖାଯିବ)
if st.session_state.app_mode == "📚 Study Masterclass" and st.session_state.stage in ["quiz_evaluation", "completion"] and st.session_state.current_session_id:
    st.markdown("### 📥 Download Your Materials")
    col_a, col_b = st.columns(2)
    
    with col_a:
        if st.session_state.main_notes is None:
            if st.button("📄 Generate Main Study Notes", use_container_width=True):
                with st.spinner("Compiling massive notes..."):
                    llm_dl = ChatOllama(model="llama3.2:1b", temperature=0.5)
                    notes_prompt = f"Create a very deep, comprehensive summary document for '{st.session_state.topic}' in {selected_language}. Use clear bullet points and headings."
                    notes_response = llm_dl.invoke(notes_prompt)
                    st.session_state.main_notes = create_file(f"{st.session_state.topic} - Main Notes", notes_response.content)
                    st.rerun()
        else:
            st.download_button(
                label="⬇️ Download Study Notes",
                data=st.session_state.main_notes,
                file_name=f"{st.session_state.topic}_Notes.md",
                mime="text/markdown",
                use_container_width=True
            )
                
    with col_b:
        if st.session_state.quiz_book is None:
            if st.button("📝 Generate MCQ Quiz Book", use_container_width=True):
                with st.spinner("Compiling quiz..."):
                    llm_dl = ChatOllama(model="llama3.2:1b", temperature=0.3)
                    quiz_prompt = f"Create a test paper with 5 MCQs and their Answer Key for '{st.session_state.topic}' in {selected_language}."
                    quiz_response = llm_dl.invoke(quiz_prompt)
                    st.session_state.quiz_book = create_file(f"{st.session_state.topic} - Practice Quiz", quiz_response.content)
                    st.rerun()
        else:
            st.download_button(
                label="⬇️ Download Quiz",
                data=st.session_state.quiz_book,
                file_name=f"{st.session_state.topic}_Quiz.md",
                mime="text/markdown",
                use_container_width=True
            )

# Input Box ର Placeholder ଟେକ୍ସଟ୍ ମୋଡ୍ ଅନୁସାରେ ବଦଳିବ
input_placeholder = "Ask anything..." if st.session_state.app_mode == "💬 Casual Chat" else "Enter a topic (e.g., Python, SQL)..."
user_input = st.chat_input(input_placeholder, key="main_chat_input")

if user_input:
    
    llm = ChatOllama(model="llama3.2:1b", temperature=0.4)

    if st.session_state.current_session_id is None:
        st.session_state.current_session_id = db_manager.create_new_session(topic=user_input)
        st.session_state.topic = user_input
        
    st.session_state.chat_history.append(HumanMessage(content=user_input))
    db_manager.save_message(st.session_state.current_session_id, "user", user_input)
    
    with st.chat_message("user", avatar="👤"):
        st.markdown(user_input)
        
    with st.chat_message("assistant", avatar="🤖"):
        with st.spinner("Thinking..."):
            
            try:
                # 🔴 ମୋଡ୍ ୧: Casual Chat (ଗପସପ)
                if st.session_state.app_mode == "💬 Casual Chat":
                    chat_prompt = f"""
                    You are a friendly, conversational AI companion.
                    Respond naturally and warmly to the user's input: '{user_input}'.
                    CRITICAL RULE: Respond ENTIRELY in the {selected_language} language.
                    Do not teach or provide educational levels unless explicitly asked. Keep it casual and human-like.
                    """
                    response = llm.invoke(chat_prompt)
                    st.markdown(response.content)

                # 🔴 ମୋଡ୍ ୨: Study Masterclass (ପାଠପଢା)
                else:
                    persona_instruction = f"""
                    You are an advanced AI Master Tutor. 
                    CRITICAL RULES:
                    1. Respond ENTIRELY in the {selected_language} language.
                    2. Never print your internal tags or instructions.
                    3. Keep your response clean and well-formatted.
                    """
                    
                    # ---------------------------------------------------------
                    # STAGE 0: Topic Selection -> Generate 3 Bullet Point Levels
                    # ---------------------------------------------------------
                    if st.session_state.stage == "topic_selection":
                        prompt = f"""
                        The user wants to learn about: '{user_input}'.
                        {persona_instruction}
                        
                        YOUR TASK:
                        1. Provide a short introduction to the topic.
                        2. Explain what they will learn at 3 different levels. 
                        3. YOU MUST FORMAT THE LEVELS AS A BULLETED LIST. Put each level on a new line with a 2-sentence explanation. Use this exact format:
                           * **Beginner Level:** [Your explanation here]
                           * **Intermediate Level:** [Your explanation here]
                           * **Advanced Level:** [Your explanation here]
                        4. End your response EXACTLY with this question: "Which level or levels would you like to study?"
                        """
                        response = llm.invoke(prompt)
                        st.markdown(response.content)
                        st.session_state.stage = "level_selection"

                    # ---------------------------------------------------------
                    # STAGE 1: Level Selected -> Provide Schedule ONLY
                    # ---------------------------------------------------------
                    elif st.session_state.stage == "level_selection":
                        prompt = f"""
                        Topic: '{st.session_state.topic}'. 
                        Levels chosen: '{user_input}'.
                        {persona_instruction}
                        
                        YOUR TASK:
                        Create a Study Schedule. YOU MUST USE BULLET POINTS AND LINE BREAKS.
                        Format exactly like this:
                        
                        * 📅 **Total Days:** [Your answer]
                        * ⏰ **Study Time:** [Your answer]
                        * ☕ **Break Schedule:** [Your answer]
                        
                        DO NOT EXPLAIN THE TOPIC YET.
                        End EXACTLY with a new line saying: "Please reply 'Start' whenever you are ready to begin the lesson."
                        """
                        response = llm.invoke(prompt)
                        st.markdown(response.content)
                        st.session_state.stage = "wait_for_start"

                    # ---------------------------------------------------------
                    # STAGE 2: User says "Start" -> DEEP EXPLANATION 
                    # ---------------------------------------------------------
                    elif st.session_state.stage == "wait_for_start":
                        if any(word in user_input.lower() for word in ["start", "yes", "ok", "ready", "ହଁ", "ଆରମ୍ଭ"]):
                            prompt = f"""
                            Topic: '{st.session_state.topic}'
                            {persona_instruction}
                            
                            YOUR TASK:
                            You must act as a Master Professor. Provide an EXTREMELY DETAILED explanation of the topic.
                            1. Break the topic down minutely. 
                            2. YOU MUST USE BULLET POINTS, BOLD TEXT, AND PROPER LINE BREAKS for readability. Do not write long boring paragraphs.
                            3. Use multiple real-world examples, analogies, and code blocks (if technical) to make every single concept crystal clear.
                            End your massive explanation EXACTLY with a new line saying: "Please reply 'Quiz' to test your knowledge."
                            """
                            response = llm.invoke(prompt)
                            st.session_state.stage = "wait_for_quiz"
                        else:
                            prompt = f"Politely tell the user to reply 'Start' when they are ready to read the full explanation. {persona_instruction}"
                            response = llm.invoke(prompt)
                        st.markdown(response.content)

                    # ---------------------------------------------------------
                    # STAGE 3: User says "Quiz" -> Generate MCQs
                    # ---------------------------------------------------------
                    elif st.session_state.stage == "wait_for_quiz":
                        if any(word in user_input.lower() for word in ["quiz", "test", "yes", "ok", "ready"]):
                            prompt = f"""
                            Topic: '{st.session_state.topic}'
                            {persona_instruction}
                            
                            YOUR TASK:
                            Generate exactly 3 Multiple Choice Questions (MCQs) based on the deep lesson you just taught.
                            Present the options clearly (A, B, C, D) using line breaks, and ask the user to reply with their answers.
                            """
                            response = llm.invoke(prompt)
                            st.session_state.stage = "quiz_evaluation"
                        else:
                            prompt = f"Ask the user to reply 'Quiz' to take the test. {persona_instruction}"
                            response = llm.invoke(prompt)
                        st.markdown(response.content)
                        
                    # ---------------------------------------------------------
                    # STAGE 4: Evaluate Quiz -> Finish
                    # ---------------------------------------------------------
                    elif st.session_state.stage == "quiz_evaluation":
                        prompt = f"""
                        The user answered the quiz with: '{user_input}'.
                        {persona_instruction}
                        
                        YOUR TASK:
                        Evaluate their answers, explain the correct ones briefly, and congratulate them for completing the masterclass!
                        """
                        response = llm.invoke(prompt)
                        st.markdown(response.content)
                        st.session_state.stage = "completion"
                        
                    # ---------------------------------------------------------
                    # STAGE 5: Completion State
                    # ---------------------------------------------------------
                    elif st.session_state.stage == "completion":
                        prompt = f"Chat naturally: '🎉 You did an amazing job! Download your notes below, or click **Start New Journey** in the sidebar for a new topic.' {persona_instruction}"
                        response = llm.invoke(prompt)
                        st.markdown(response.content)
                
                # ଉଭୟ ମୋଡ୍ ପାଇଁ ଇତିହାସ (History) ସେଭ୍ ହେବ
                st.session_state.chat_history.append(AIMessage(content=response.content))
                db_manager.save_message(st.session_state.current_session_id, "assistant", response.content)

            except Exception as e:
                st.error(f"⚠️ Engine Error: {str(e)}\n\n(Ensure your local AI engine is running in the terminal.)")
                st.session_state.chat_history.pop()